.TH MINISEED2DMC 1 2008/12/04
.SH NAME
miniseed2dmc \- Transfer Mini-SEED data to the IRIS Data Managment Center
.SH SYNOPSIS
.nf
miniseed2dmc [options] host:port files|directories

.fi
.SH DESCRIPTION
\fBminiseed2dmc\fP transfers selected Mini-SEED data records to the
IRIS Data Managment Center.  Prior to using this program coordination
with DMC is required and the user must have been assigned a host and
port indicating where the data should be sent.

This transfer method is not file based, Mini-SEED records are sent
individually and reassembled at the DMC into files

Input files or directories or list files '@'

SYNC file.

state file.

not real-time.

.SH OPTIONS

.IP "-V"
Print the program version and exit.

.IP "-h"
Print the program help/usage and exit.

.IP "-v"
Be more verbose.  This flag can be used multiple times ("-v -v" or 
"-vv") for more verbosity.

.IP "-r \fIlevel\fP"
Specify the maximum number of directories to recurse into, default is
no limits.

.IP "-E"
Exit the program on connection errors.  By default miniseed2dmc will
continuously try to connect to the specified server until all data has
been sent.

.IP "-q"
Be quiet, do not print the default diagnostic messages or transmission
summary.

.IP "-NS"
Do not write a SYNC file after sending data, by default a SYNC file
representing the data set sent is written for each session.  All SYNC
files are written to the "work directory" (the \fB-w\fP option).

.IP "-ACK"
Request and require acknowledgements from the server for each
Mini-SEED record sent.  This should not be necessary since TCP
performs this function, it will also significantly slow down the
transfer rate.

.IP "-I"
Print the transfer rate at a specified interval (the \fB-It\fP option)
during transmission.

.IP "-It \fIinterval\fP"
Specify \fIinterval\fP in seconds at which to print transfer rate
statistics during transmission, default is 30 seconds.  This option
implies the \fB-I\fP option.

.IP "-w \fIworkdir\fP"
The working directory is where the state file and SYNC listing will be
written, default is the current working directory.  A recommended 

.IP "-S \fIstatefile\fP"
A state file is written to track the status of the transmission, a
uniqe state file should be used for each separate data set.  By
default a file named "statefile" will be written to the \fBworkdir\fP.

.IP "-l \fIlistfile\fP"
The \fIlistfile\fP is a file containing a list of files and/or
directories containing Mini-SEED to be sent.  This is an alternative
to prefixing an input file with the '@' which identifies it as a list
file.

.IP "\fIhost:port\fP"
The required host and port arguments specify the server where the
Mini-SEED records should be sent.

.SH "EXAMPLES"



.SH AUTHOR
.nf
Chad Trabant
IRIS Data Management Center
.fi
