.TH MINISEED2DMC 1 2008/12/05
.SH NAME
miniseed2dmc \- Transfer Mini-SEED data to the IRIS DMC
.SH SYNOPSIS
.nf
miniseed2dmc [options] host:port files|directories ...

.fi
.SH DESCRIPTION
\fBminiseed2dmc\fP transfers selected Mini-SEED data records to the
IRIS Data Managment Center.  Prior to using this program coordination
with DMC is required and the user must have been assigned a host and
port indicating where the data should be sent.

Mini-SEED to be transfered can be identified 3 different ways:
.nf
1 - files on the command line
2 - directories on the command line which will be searched
3 - files containing lists of files and/or directories 
.fi 

If directories are specified on the command line or in list files all
files they contain are assumed to be input files and all
sub-directories will be searched (the level of recursion can be
limited with the \fB-r\fP option).

List files are identified by prefixing the file name with '@' on the
command line or by using the \fB-l\fP option.

A state file is maintained by \fBminiseed2dmc\fP to track the progress
of data transfer.  This tracking means that the client can be shut
down and then resume the transfer when the client is restarted.  More
importantly it allows the client to determine when all records from a
given data set have been transferred preventing them from being
transferred again erroneously.  By default the state file is written
to a file named, creatively, 'statefile' in the working directory (see
the \fB-w\fP option).  The default state file location may be
overridden using the \fB-S\fP option.

To track the Mini-SEED data transferred \fBminiseed2dmc\fP writes SYNC
files representing the data coverage.  The SYNC files are written to
the working directory (see the \fB-w\fP option).  The SYNC file names
contain the connection start and end times as a record of when the
data was sent.  A separate SYNC file listing is written for each time
the program is executed.

.SH OPTIONS

.IP "-V"
Print the program version and exit.

.IP "-h"
Print the program help/usage and exit.

.IP "-v"
Be more verbose.  This flag can be used multiple times ("-v -v" or 
"-vv") for more verbosity.

.IP "-p"
Pretend, process input files as usual and write the state file and
SYNC file but do not connect or send data to the submission server.
Useful for client side testing, the transfer statistics will not be
accurate.  After running the program in this mode the state file (and
probably the SYNC file) created must be removed prior to actually
transferring the data.

.IP "-r \fIlevel\fP"
Specify the maximum number of directories to recurse into, default is
no limits.

.IP "-E"
Exit the program on connection errors.  By default miniseed2dmc will
continuously try to connect to the specified server until all data has
been sent.

.IP "-q"
Be quiet, do not print the default diagnostic messages or transmission
summary.

.IP "-NS"
Do not write a SYNC file after sending data, by default a SYNC file
representing the data set sent is written for each session.  All SYNC
files are written to the "work directory" (the \fB-w\fP option).

.IP "-ACK"
Request and require acknowledgements from the server for each
Mini-SEED record sent.  This should not be necessary since TCP
performs this function, it will also significantly slow down the
transfer rate.

.IP "-I"
Print the transfer rate at a specified interval (the \fB-It\fP option)
during transmission.

.IP "-It \fIinterval\fP"
Specify \fIinterval\fP in seconds at which to print transfer rate
statistics during transmission, default is 30 seconds.  This option
implies the \fB-I\fP option.

.IP "-w \fIworkdir\fP"
The working directory is where the state file and SYNC listing will be
written, default is the current working directory.  A recommended 

.IP "-S \fIstatefile\fP"
A state file is written to track the status of the transmission, a
uniqe state file should be used for each separate data set.  By
default a file named "statefile" will be written to the \fBworkdir\fP.

.IP "-l \fIlistfile\fP"
The \fIlistfile\fP is a file containing a list of files and/or
directories containing Mini-SEED to be sent.  This is an alternative
to prefixing an input file with the '@' which identifies it as a list
file.

.IP "\fIhost:port\fP"
The required host and port arguments specify the server where the
Mini-SEED records should be sent.

.SH "EXAMPLES"
For the below examples the host and port are specified as
\fBhost:port\fP, in real usage these must be a real host name and
port.

.IP "Example 1"
The most simple example is sending a couple of files containing
Mini-SEED:

.nf
> miniseed2dmc host:port 080101.mseed 080102.mseed
.fi

In this case the state file and SYNC files will be written to the
current directory.

.IP "Example 2"
If there is a directory called 'data' that contains only files of
Mini-SEED they can all be sent using:

.nf
> miniseed2dmc host:port data
.fi

The program automatically distinguishes between files and directories.

.IP "Example 3"
A list file named 'mseeds.txt' contains:
.nf
---- mseeds.txt
/data/080101.mseed
/data/080102.mseed
----
.fi

This file can be used with miniseed2dmc using the follow sytax (both
are equivalent):

.nf
> miniseed2dmc host:port @mseeds.txt
> miniseed2dmc host:port -l mseeds.txt
.fi

.IP "Example 4"
A recommended organization of data is to have a directory for each
data set and keep all the Mini-SEED files in a sub-directory.  For
example, a monthly data set can be kept in /archive/Jan2008/ with all
the January 2008 Mini-SEED files kept in /archive/Jan2008/data/.
\fBminiseed2dmc\fP could then we executed in the following manner:

.nf
> miniseed2dmc host:port -w /archive/Jan2008/ /archive/Jan2008/data/
.fi

This will result in all the Mini-SEED data in /archive/Jan2008/data/
being transferred and the related state and SYNC file(s) being written
to /archive/Jan2008/.

.SH "NOTES"
This transfer method is not file based, Mini-SEED records are sent
individually and reassembled at the DMC into files useful for the DMC
archiving process.  The DMC will have no information regarding the
file names, sizes, etc. from which the records were transferred.

This program is intended to transfer static data sets, it is not
designed for transfer of real-time streaming data.

.SH AUTHOR
.nf
Chad Trabant
IRIS Data Management Center
.fi
